stages:
  - test

pytest:
  stage: test
  image: python:3.12
  variables:
    PYTHONPATH: "$CI_PROJECT_DIR"
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -e .
  script:
    - pytest --junitxml=pytest-results.xml
  artifacts:
    when: always
    reports:
      junit: pytest-results.xml
    paths:
      - pytest-results.xml