stages:
  - pytest
  - docker_build

pytest:
  stage: pytest
  image: python:3.12
  variables:
    PYTHONPATH: "$CI_PROJECT_DIR"
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -e .
  script:
    - pytest --junitxml=pytest-results.xml
  artifacts:
    when: always
    reports:
      junit: pytest-results.xml
    paths:
      - pytest-results.xml


docker_build:
  stage: docker_build
  image: docker:24.0.5
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t registry.gitlab.com/$CI_PROJECT_PATH:latest .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push registry.gitlab.com/$CI_PROJECT_PATH:latest