stages:
  - test

pytest_job:
  stage: test
  image: python:3.12
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest --junitxml=pytest-results.xml
  artifacts:
    when: always
    reports:
      junit: pytest-results.xml
    expire_in: 1 hour