paths:
  data_root: data
  
  raw:
    commodities:
      gold: raw/commodities/gold.parquet
      oil: raw/commodities/oil.parquet
    ftse: raw/ftse
    fx:
      gbp_eur: raw/fx/gbp_eur.parquet
      gbp_usd: raw/fx/gbp_usd.parquet
    rf:
      rf: raw/rf/rf.parquet
    index: raw/index.parquet
    all_tickers: raw/all_tickers.parquet
    
  processed: processed

  inference: inference/inference.parquet